# Generated by Django 5.0.4 on 2024-05-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_conversation',
            name='name',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
